### ISSUE TITLE
syntax or sample needed for EK ITEM Set rules

### ISSUE THREAD

**Issue by ArminDeeg** [miyako/4d-plugin-event-kit#10]
Hi Miyako,

how to use this command ?
**EK ITEM Set rules** 

recurranceCount:=3
recurranceInterval:=2
recurranceType="weekly"

**Comment by ArminDeeg** [comment]
Ok, I see inside the source code that the feature is not implemented

`void EK_ITEM_Set_rules(PA_PluginParameters params) {

    if(request_permission_granted_for_events) {
        
    }
}`

So what can I do ?  the plugin iCal v3 uses a deprecated API and Event kit is not complete

**Comment by miyako** [comment]
This is speculation, but I think Apple deprecated the CalendarStore API in OS X **10.5** to have a new (and limited) API that was the same for **iOS** and for Mac. The reality seems to be that the deprecated API seems to be redirected to the new one anyway. It is not often the case the a deprecated API works 10 version later (**10.15**),

Maintaining these plugins is not a priority for me at the moment, because none of my clients in Japan are using them, and when users from outside of Japan occasionally contact me for an update via Professional Services and we give a quote, they say "no thanks, not that important".

**Comment by miyako** [comment]
Some time ago I was a bit bored and wanted a distraction, so I made "v3" as a first step to clean up and refactor the messy code (**iCal** was one of my first ever plugins).

**Comment by miyako** [comment]
I think it is time to archive this repo.

Work will continue on [ical-v3](https://github.com/miyako/4d-plugin-ical-v3)
